# Generated by Django 5.0.7 on 2024-07-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='рейтинг'),
        ),
    ]
